version: '3.8'

services:
  bot:
    build: .
    container_name: gemini-summary-bot
    restart: always
    network_mode: "host"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CSE_ID=${GOOGLE_CSE_ID}
      - LLM_MODEL=${LLM_MODEL:-gemini-flash-latest}
      - TS_LANG=${TS_LANG:-Russian}
      - CHUNK_SIZE=100000
      - WEBAPP_URL=${WEBAPP_URL}
      - ALLOWED_USERS=${ALLOWED_USERS}
