version: '3.8'

services:
  bot:
    build: .
    container_name: gemini-summary-bot
    network_mode: "host"
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LLM_MODEL=gemini-flash-lite-latest
      - TS_LANG=Russian
      - CHUNK_SIZE=100000